repo: github.com/d-kuro/approve-bot
owners:
  - name: d-kuro
    patterns:
      - path/to/file
      - regexp
      - cmd/approve.go
      - cmd/[a-z]+.go
  - name: d-kuro-kuro
    patterns:
      - path/to/file
      - regexp
      - cmd/version.go
      - cmd/.+
