builds:
  - main: main.go
    binary: approve-bot
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/d-kuro/approve-bot/cmd.Revision={{ .ShortCommit }}
