name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - 1.12.9
    name: Go ${{ matrix.go }} build
    steps:
    - uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        version: ${{ matrix.go }}
    - name: Run go mod download
      run: go mod download
    - name: Install golangci-lint
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1
        # https://github.com/golangci/golangci-lint/issues/250
        sudo mv ./bin/golangci-lint $GOPATH/bin/
    - name: Run golangci-lint
      run: >
        golangci-lint run \
          --tests \
          --enable-all \
          --disable gochecknoglobals \
          --disable gochecknoinits
    - name: Run tests
      run: go test -race -v ./...
